### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by rag4214**
Lots of stuff here. 

First, auth using google Oauth2. All the routes and models to go with it too.

Second. Completely redone frontend.

### CODE REVIEW

**Comment by evanextreme** [comment]
This should probably be merged with `develop` not `master`, to adhere to git flow standards

**Comment by rag4214** [comment]
I would if we had a `develop` server but we don't so it's going to master

**Comment by evanextreme** [comment]
@rag4214 we don’t have a dev server, but this should be merged with `develop` and then PR’d with `master` once integration testing has been finished

**Comment by NeilBeforeMemes** [comment]
I agree - merging to `develop` the way to go. It's important not to break the proper git flow process

**Comment by NeilBeforeMemes** [comment]
Also - @rag4214 you only commented in 5 out of **180** changed files - that's not sufficient

**Comment by rag4214** [comment]
Would you like me to comment all of the angular components as well?

**Pull request merged**
